const mongoose = require('mongoose');
const { ObjectId } = mongoose.Schema;

const userSchema = new mongoose.Schema(
  {
    name: String,
    email: {
      type: String,
      required: true,
      index: true,
    },
    username: {
      type: String,
      unique: true,
      required: true,
    },
    role: {
      type: String,
      default: 'subscriber',
    },
    about: {},
    profileImage: {
      url: String,
      pulic_id: String,
    },
    coverImage: {
      url: String,
      pulic_id: String,
    },
    gender: String,
    location: String,
    genderWanted: String,
    relWanted: String,
    birthday: Date,
    following: [{ type: ObjectId, ref: 'User' }],
    followers: [{ type: ObjectId, ref: 'User' }],
    matches: [{ type: ObjectId, ref: 'User' }],
    nopes: [{ type: ObjectId, ref: 'User' }],
    visitors: [{ type: ObjectId, ref: 'User' }],
    profilePhotos: Array,
    coverPhotos: Array,
    uploadedPhotos: Array,
    cart: {
      type: Array,
      default: [],
    },
    address: Object,
    wishlist: [{ type: ObjectId, ref: 'Product' }],
    // points: { type: Number, awarded: { type: Date, default: Date.now } },
    pointsGained: [
      {
        amount: Number,
        reason: String,
        awarded: { type: Date, default: Date.now },
      },
    ],
    pointsLost: [
      {
        amount: Number,
        reason: String,
        removed: { type: Date, default: Date.now },
      },
    ],
    notifications: [
      {
        // notif: { type: ObjectId, ref: 'Post' },
        notif: {},
        action: String,
        occurred: { type: Date, default: Date.now },
        new: { type: Boolean, default: true },
      },
    ],
    featuredMember: {
      type: Boolean,
      default: false,
    },
    events: [
      {
        name: String,
        location: Object,
        when: Date,
        notes: String,
        invitees: [],
        cancelled: Boolean,
        going: String,
      },
    ],
    language: String,
    maritalStatus: String,
    numOfChildren: Number,
    drinks: String,
    smokes: String,
    nationality: String,
    height: String,
    build: String,
    hairStyle: String,
    hairLength: String,
    eyeColor: String,
    ethnicity: String,
    feetType: String,
    loves: Array,
    hates: Array,
    education: String,
    occupation: String,
    politics: String,
    religion: String,
    pets: Array,
    interests: Array,
    music: Array,
    foods: String,
    books: Array,
    films: Array,
    sports: Array,
    livesWith: String,
    roleInLife: String,
    managesEdu: String,
    hobbies: Array,
    marriage: String,
    income: String,
    ageOfPartner: String,
    traits: Array,
    changes: String,
    relocate: String,
    treatSelf: Array,
    sexLikes: String,
    sexFrequency: String,
  },
  { timestamps: true }
);

module.exports = mongoose.model('User', userSchema);
